name: Push File from Shortcut

on:
  workflow_dispatch:
    inputs:
      filedata:
        description: 'pathと中身を適切に形成してstringで渡す'
        required: true
        type: string

permissions:
  contents: write

jobs:
  commit-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test
        run: |
          echo "The message is: ${{ inputs.filedata }}"