name: Deploy Python Generated HTML to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチへのPush時に実行
    paths:
      - 'content/**/*.md'         # Markdownファイル変更時
      - 'scripts/**/*.py'         # 変換スクリプト変更時
      #- '.github/workflows/*.yml' # ワークフロー定義ファイル変更時

# GitHub Pagesの自動デプロイに必要なアクセス権限
permissions:
  contents: read
  pages: write

# 連続Push時に古い実行を自動キャンセルして最新ビルドを優先
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードを作業領域にチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Python環境のセットアップ (今回のスクリプトは標準ライブラリのみで動作するため pip install は不要)
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      # 3. Pythonスクリプトを実行して content/*.md から dist/*.html を生成
      - name: Run Python
        run: python scripts/test.py
      
      # 4. 変更したファイルをpush
      - name: Git Setup
        run: |
          git config pull.ff only user.name "tajima27831"
          git config pull.ff only user.email "tiandaoguanghui@gmail.com"
          git add .
          got commit -m "test" -a
          git pull
          git push