name: Generate HTML

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードを作業領域にチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2. Python環境のセットアップ (今回のスクリプトは標準ライブラリのみで動作するため pip install は不要)
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      # 更新のあったmdファイルのパスをpythonに渡す？
      # 3. Pythonスクリプトを実行
      - name: Run Python
        run: python scripts/test.py ../math/entrance-exam/entrance-exam.md
      
      # 4. 変更したファイルをpush
      - name: Git Setup
        run: |
          git config --local user.email "github-actions[bot]@://github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if ! git diff --cached --exit-code --quiet; then
            git commit -m "chore: auto-update output.txt via GitHub Actions"
            git push
          else
            echo "No changes detected. Skipping commit."
          fi