name: check diff

on:
  push:
    paths:
        - '**.md'

env:
  BASE_DIR: "./"

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
    
      - name: check files
        run: |
          git fetch origin "${{ github.event.before }}" --depth=1

          TARGETS=$(git diff -z --name-only --diff-filter=ACMR "${{ github.event.before }}.." -- '*.md'| tr '\0' '\n')

          echo "=== Detected Target Files ==="
          if [ -z "${TARGETS}" ]; then
            echo "No matching changed files found."
          else
            echo "${TARGETS}"
          fi
          echo "============================="

          printf "TARGETS<<EOF\n%s\nEOF\n" "${TARGETS}" >> $GITHUB_ENV